version: "3"
services:
  nas-tools:
    # 1. Name of your private local image
    image: hiemas-a11y/nas-tools:latest
    # 2. This builds it locally on your server from your files
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000        
    volumes:
      - ./config:/config   
      # 3. This unified path is the secret to making hardlinks work instantly!
      # Change "/home/youruser/data" to the actual main directory on your server where your torrents AND media live.
      - /home/youruser/data:/data   
    environment: 
      - PUID=0    
      - PGID=0    
      - UMASK=000 
      - NASTOOL_AUTO_UPDATE=true  
      - NASTOOL_CN_UPDATE=false 
      - REPO_URL=https://github.com/hiemas-a11y/nas-tools.git  
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools
